//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package paqueteVista;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;
import java.util.Objects;
import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;

public class vistaLogin extends JFrame {
    private JPanel Ventana;
    private JButton BtnIngresar;
    private JLabel lineaStatus;
    private JLabel lineaTxt1;
    private JLabel lineaTxt2;
    private JTextField txtNombre1;
    private JTextField txtNombre2;

    public vistaLogin() {
        this.setContentPane(this.Ventana);
        this.setTitle("Login");
        this.setDefaultCloseOperation(3);
        this.pack();
        this.setSize(600, 400);
        this.setLocationRelativeTo((Component) null);
    }

    public JButton getBtnIngresar() {
        return this.BtnIngresar;
    }

    public JTextField getTxtNombre2() {
        return this.txtNombre2;
    }

    public JTextField getTxtNombre1() {
        return this.txtNombre1;
    }

    public JLabel getLineaStatus() {
        return this.lineaStatus;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Ventana = new JPanel();
        Ventana.setLayout(new GridLayoutManager(8, 6, new Insets(0, 0, 0, 0), -1, -1));
        Ventana.setBackground(new Color(-7693387));
        final JLabel label1 = new JLabel();
        label1.setEnabled(true);
        Font label1Font = this.$$$getFont$$$("Cambria", Font.BOLD | Font.ITALIC, 28, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-1511169));
        label1.setText("Login 4 en Linea");
        Ventana.add(label1, new GridConstraints(0, 0, 3, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lineaTxt1 = new JLabel();
        Font lineaTxt1Font = this.$$$getFont$$$("Consolas", Font.BOLD | Font.ITALIC, 16, lineaTxt1.getFont());
        if (lineaTxt1Font != null) lineaTxt1.setFont(lineaTxt1Font);
        lineaTxt1.setForeground(new Color(-1445121));
        lineaTxt1.setText("Ingrese el nombre del primer jugador");
        Ventana.add(lineaTxt1, new GridConstraints(3, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lineaTxt2 = new JLabel();
        lineaTxt2.setEnabled(true);
        Font lineaTxt2Font = this.$$$getFont$$$("Consolas", Font.BOLD | Font.ITALIC, 16, lineaTxt2.getFont());
        if (lineaTxt2Font != null) lineaTxt2.setFont(lineaTxt2Font);
        lineaTxt2.setForeground(new Color(-1577217));
        lineaTxt2.setText("Ingrese el nombre del segundo jugador");
        Ventana.add(lineaTxt2, new GridConstraints(4, 0, 2, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtNombre1 = new JTextField();
        txtNombre1.setBackground(new Color(-9009247));
        txtNombre1.setForeground(new Color(-16719617));
        Ventana.add(txtNombre1, new GridConstraints(3, 3, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtNombre2 = new JTextField();
        txtNombre2.setBackground(new Color(-9009247));
        txtNombre2.setForeground(new Color(-16719617));
        Ventana.add(txtNombre2, new GridConstraints(4, 3, 2, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lineaStatus = new JLabel();
        lineaStatus.setForeground(new Color(-1576705));
        lineaStatus.setText("");
        Ventana.add(lineaStatus, new GridConstraints(7, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, 1, 1, null, null, null, 0, false));
        BtnIngresar = new JButton();
        BtnIngresar.setBackground(new Color(-6902070));
        BtnIngresar.setHorizontalTextPosition(0);
        BtnIngresar.setText("Ingresar");
        Ventana.add(BtnIngresar, new GridConstraints(6, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 35), new Dimension(150, 35), 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Ventana;
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */


}
