//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package paqueteVista;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Objects;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class vistaLogin extends JFrame {
    private JPanel Ventana;
    private JLabel textoLogin;
    private JButton BtnIngresar;
    private JTextArea lineaStatus;
    private JLabel lineaTxt1;
    private JLabel lineaTxt2;
    private JTextField txtNombre1;
    private JTextField txtNombre2;
    private JScrollPane JScrollPane;

    public vistaLogin() {
        this.setContentPane(this.Ventana);
        this.setTitle("Login");
        this.setDefaultCloseOperation(3);
        this.pack();
        this.setSize(600, 400);
        this.setLocationRelativeTo((Component) null);
        this.BtnIngresar.addActionListener(new ActionListener() {
            {
                Objects.requireNonNull(vistaLogin.this);
            }

            public void actionPerformed(ActionEvent e) {
            }
        });
    }

    public JButton getBtnIngresar() {
        return this.BtnIngresar;
    }

    public JTextField getTxtNombre2() {
        return this.txtNombre2;
    }

    public JTextField getTxtNombre1() {
        return this.txtNombre1;
    }

    public JTextArea getLineaStatus() {
        return this.lineaStatus;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
    }
}
