package paqueteVista;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class vistaTablero extends JFrame {

    private JPanel panelPrincipal;
    private JLabel infoTurno;
    private JButton btnColumna1;
    private JButton btnColumna2;
    private JButton btnColumna3;
    private JButton btnColumna4;
    private JButton btnColumna5;
    private JButton btnColumna6;
    private JButton btnColumna7;
    private JButton celda00;
    private JButton celda04;
    private JButton celda01;
    private JButton celda02;
    private JButton celda03;
    private JButton celda05;
    private JButton celda06;
    private JButton celda10;
    private JButton celda11;
    private JButton celda12;
    private JButton celda13;
    private JButton celda14;
    private JButton celda15;
    private JButton celda16;
    private JButton celda20;
    private JButton celda21;
    private JButton celda22;
    private JButton celda23;
    private JButton celda24;
    private JButton celda25;
    private JButton celda26;
    private JButton celda30;
    private JButton celda31;
    private JButton celda32;
    private JButton celda33;
    private JButton celda34;
    private JButton celda35;
    private JButton celda36;
    private JButton celda40;
    private JButton celda41;
    private JButton celda42;
    private JButton celda43;
    private JButton celda44;
    private JButton celda45;
    private JButton celda46;
    private JButton celda50;
    private JButton celda51;
    private JButton celda52;
    private JButton celda53;
    private JButton celda54;
    private JButton celda55;
    private JButton celda56;
    private JPanel seleccionColumnas;
    private JPanel tablero;
    private JLabel avisoLlena;

    public vistaTablero() {
        setContentPane(panelPrincipal);
        setTitle("4 en linea");
        setSize(700, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    public JLabel getInfoTurno() {
        return infoTurno;
    }

    public JLabel getAvisoLlena() {
        return avisoLlena;
    }

    public JPanel getSeleccionColumnas() {
        return seleccionColumnas;
    }

    public JPanel getTablero() {
        return tablero;
    }

    private JButton[][] botonesTablero;

    public void creacionArrayTablero() {
        botonesTablero = new JButton[][]{
                {celda00, celda01, celda02, celda03, celda04, celda05, celda06},
                {celda10, celda11, celda12, celda13, celda14, celda15, celda16},
                {celda20, celda21, celda22, celda23, celda24, celda25, celda26},
                {celda30, celda31, celda32, celda33, celda34, celda35, celda36},
                {celda40, celda41, celda42, celda43, celda44, celda45, celda46},
                {celda50, celda51, celda52, celda53, celda54, celda55, celda56}
        };
    }

    public JButton[][] getBotonesTablero() {
        return botonesTablero;
    }

    private JButton[] botonesColumnas;

    public void creacionArrayColumnas() {
        botonesColumnas = new JButton[]{
                btnColumna1, btnColumna3, btnColumna4,
                btnColumna5, btnColumna2,
                btnColumna6, btnColumna7
        };
    }

    public JButton[] getBotonesColumna() {
        return botonesColumnas;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelPrincipal = new JPanel();
        panelPrincipal.setLayout(new GridLayoutManager(4, 1, new Insets(7, 0, 0, 0), -1, -1));
        panelPrincipal.setBackground(new Color(-7693387));
        infoTurno = new JLabel();
        Font infoTurnoFont = this.$$$getFont$$$("Consolas", Font.BOLD | Font.ITALIC, 24, infoTurno.getFont());
        if (infoTurnoFont != null) infoTurno.setFont(infoTurnoFont);
        infoTurno.setForeground(new Color(-1508865));
        infoTurno.setText("");
        panelPrincipal.add(infoTurno, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        seleccionColumnas = new JPanel();
        seleccionColumnas.setLayout(new GridLayoutManager(1, 7, new Insets(0, 5, 0, 5), -1, -1));
        seleccionColumnas.setAlignmentX(1.0f);
        seleccionColumnas.setAlignmentY(1.0f);
        seleccionColumnas.setBackground(new Color(-7693387));
        panelPrincipal.add(seleccionColumnas, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, true));
        btnColumna1 = new JButton();
        btnColumna1.setText("↓");
        seleccionColumnas.add(btnColumna1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        btnColumna2 = new JButton();
        btnColumna2.setText("↓");
        seleccionColumnas.add(btnColumna2, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        btnColumna3 = new JButton();
        btnColumna3.setText("↓");
        seleccionColumnas.add(btnColumna3, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        btnColumna4 = new JButton();
        btnColumna4.setText("↓");
        seleccionColumnas.add(btnColumna4, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        btnColumna5 = new JButton();
        btnColumna5.setText("↓");
        seleccionColumnas.add(btnColumna5, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        btnColumna6 = new JButton();
        btnColumna6.setText("↓");
        seleccionColumnas.add(btnColumna6, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        btnColumna7 = new JButton();
        btnColumna7.setText("↓");
        seleccionColumnas.add(btnColumna7, new GridConstraints(0, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        tablero = new JPanel();
        tablero.setLayout(new GridLayoutManager(6, 7, new Insets(7, 5, 7, 5), -1, -1));
        tablero.setBackground(new Color(-10385739));
        panelPrincipal.add(tablero, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        celda00 = new JButton();
        celda00.setActionCommand("");
        celda00.setEnabled(false);
        celda00.setText("");
        tablero.add(celda00, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda04 = new JButton();
        celda04.setEnabled(false);
        celda04.setText("");
        tablero.add(celda04, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda01 = new JButton();
        celda01.setEnabled(false);
        celda01.setText("");
        tablero.add(celda01, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda02 = new JButton();
        celda02.setEnabled(false);
        celda02.setText("");
        tablero.add(celda02, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda03 = new JButton();
        celda03.setEnabled(false);
        celda03.setText("");
        tablero.add(celda03, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda06 = new JButton();
        celda06.setEnabled(false);
        celda06.setText("");
        tablero.add(celda06, new GridConstraints(0, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda05 = new JButton();
        celda05.setEnabled(false);
        celda05.setText("");
        tablero.add(celda05, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda10 = new JButton();
        celda10.setEnabled(false);
        celda10.setText("");
        tablero.add(celda10, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda11 = new JButton();
        celda11.setEnabled(false);
        celda11.setText("");
        tablero.add(celda11, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda12 = new JButton();
        celda12.setEnabled(false);
        celda12.setText("");
        tablero.add(celda12, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda13 = new JButton();
        celda13.setEnabled(false);
        celda13.setText("");
        tablero.add(celda13, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda14 = new JButton();
        celda14.setEnabled(false);
        celda14.setText("");
        tablero.add(celda14, new GridConstraints(1, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda15 = new JButton();
        celda15.setEnabled(false);
        celda15.setText("");
        tablero.add(celda15, new GridConstraints(1, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda16 = new JButton();
        celda16.setEnabled(false);
        celda16.setText("");
        tablero.add(celda16, new GridConstraints(1, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda20 = new JButton();
        celda20.setEnabled(false);
        celda20.setText("");
        tablero.add(celda20, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda21 = new JButton();
        celda21.setEnabled(false);
        celda21.setText("");
        tablero.add(celda21, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda22 = new JButton();
        celda22.setEnabled(false);
        celda22.setText("");
        tablero.add(celda22, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda23 = new JButton();
        celda23.setEnabled(false);
        celda23.setText("");
        tablero.add(celda23, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda24 = new JButton();
        celda24.setEnabled(false);
        celda24.setText("");
        tablero.add(celda24, new GridConstraints(2, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda25 = new JButton();
        celda25.setEnabled(false);
        celda25.setText("");
        tablero.add(celda25, new GridConstraints(2, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda26 = new JButton();
        celda26.setEnabled(false);
        celda26.setText("");
        tablero.add(celda26, new GridConstraints(2, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda30 = new JButton();
        celda30.setEnabled(false);
        celda30.setText("");
        tablero.add(celda30, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda31 = new JButton();
        celda31.setEnabled(false);
        celda31.setText("");
        tablero.add(celda31, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda32 = new JButton();
        celda32.setEnabled(false);
        celda32.setText("");
        tablero.add(celda32, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda33 = new JButton();
        celda33.setEnabled(false);
        celda33.setText("");
        tablero.add(celda33, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda34 = new JButton();
        celda34.setEnabled(false);
        celda34.setText("");
        tablero.add(celda34, new GridConstraints(3, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda35 = new JButton();
        celda35.setEnabled(false);
        celda35.setText("");
        tablero.add(celda35, new GridConstraints(3, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda36 = new JButton();
        celda36.setEnabled(false);
        celda36.setText("");
        tablero.add(celda36, new GridConstraints(3, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda40 = new JButton();
        celda40.setEnabled(false);
        celda40.setText("");
        tablero.add(celda40, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda41 = new JButton();
        celda41.setEnabled(false);
        celda41.setText("");
        tablero.add(celda41, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda43 = new JButton();
        celda43.setEnabled(false);
        celda43.setText("");
        tablero.add(celda43, new GridConstraints(4, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda44 = new JButton();
        celda44.setEnabled(false);
        celda44.setText("");
        tablero.add(celda44, new GridConstraints(4, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda45 = new JButton();
        celda45.setEnabled(false);
        celda45.setText("");
        tablero.add(celda45, new GridConstraints(4, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda46 = new JButton();
        celda46.setEnabled(false);
        celda46.setText("");
        tablero.add(celda46, new GridConstraints(4, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda42 = new JButton();
        celda42.setEnabled(false);
        celda42.setText("");
        tablero.add(celda42, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda50 = new JButton();
        celda50.setEnabled(false);
        celda50.setText("");
        tablero.add(celda50, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda51 = new JButton();
        celda51.setEnabled(false);
        celda51.setText("");
        tablero.add(celda51, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda52 = new JButton();
        celda52.setEnabled(false);
        celda52.setText("");
        tablero.add(celda52, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda53 = new JButton();
        celda53.setEnabled(false);
        celda53.setText("");
        tablero.add(celda53, new GridConstraints(5, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda54 = new JButton();
        celda54.setEnabled(false);
        celda54.setText("");
        tablero.add(celda54, new GridConstraints(5, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda55 = new JButton();
        celda55.setEnabled(false);
        celda55.setText("");
        tablero.add(celda55, new GridConstraints(5, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        celda56 = new JButton();
        celda56.setEnabled(false);
        celda56.setText("");
        tablero.add(celda56, new GridConstraints(5, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(45, 20), new Dimension(45, 20), new Dimension(45, 20), 0, false));
        avisoLlena = new JLabel();
        Font avisoLlenaFont = this.$$$getFont$$$("Copperplate Gothic Bold", -1, -1, avisoLlena.getFont());
        if (avisoLlenaFont != null) avisoLlena.setFont(avisoLlenaFont);
        avisoLlena.setForeground(new Color(-4259840));
        avisoLlena.setText("");
        panelPrincipal.add(avisoLlena, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelPrincipal;
    }

}